[snowflake]
account ="your account name"
user = ""your user name
password = "your password"
role = "your role name"
warehouse =  "your warehouse name"
database = "your database name"
schema ="your schema name"